### ISSUE TITLE
L'API ne permet pas de récupérer le planning - Code ERR_BAD_RESPONSE - Status 500

### ISSUE THREAD

**Issue by Redblockmasteur** [MauriaApp/API#1]
J'aimerais créer une intégration Mauria pour importer mon planning dans [Home Assistant](https://www.home-assistant.io/) qui maintenant supporte un calendrier. Avant de me lancer j'ai commencé à jouer avec l'API via [Swagger UI](https://mauriaapi.fly.dev/api-docs/#/). La récupération des notes et des absences, ça marche, mais pour le planning j'ai cette erreur :

```json
{
  "message": "Request failed with status code 500",
  "name": "AxiosError",
  "stack": "AxiosError: Request failed with status code 500\n    at settle (file:///workspace/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///workspace/node_modules/axios/lib/adapters/http.js:495:11)\n    at IncomingMessage.emit (node:events:527:35)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/x-www-form-urlencoded",
      "Cookie": "JSESSIONID=A0245CBB13918C0FE8E12279639D2B51",
      "Content-type": "application/x-www-form-urlencoded",
      "User-Agent": "axios/1.1.3",
      "Content-Length": "563",
      "Accept-Encoding": "gzip, deflate, br"
    },
    "method": "post",
    "url": "https://aurion.junia.com/faces/Planning.xhtml",
    "data": "javax.faces.partial.ajax=true&javax.faces.source=form%3Aj_idt118&javax.faces.partial.execute=form%3Aj_idt118&javax.faces.partial.render=form%3Aj_idt118&form%3Aj_idt118=form%3Aj_idt118&form%3Aj_idt118_start=NaN&form%3Aj_idt118_end=NaN&form=form&form%3AlargeurDivCenter=1236&form%3Adate_input=undefined&form%3Aweek=NaN-NaN&form%3Aj_idt118_view=agendaWeek&form%3AoffsetFuseauNavigateur=-3600000&form%3Aonglets_activeIndex=0&form%3Aonglets_scrollState=0&form%3Aj_idt236_focus=&form%3Aj_idt236_input=44323&javax.faces.ViewState=576226992896720929%3A4110629706297603515"
  },
  "code": "ERR_BAD_RESPONSE",
  "status": 500
}
```

**Comment by MylowMntr** [comment]
J'avais pas vu l'issue désooo x)

BREF, effectivement, il manquait des paramètres dans la doc, j'ai fix ca, tu peux maintenant récup !

Hésites pas à m'envoyer un mail si t'as besoin d'aide rapidement!
